Update README.md
ad2476/geocoding-python-tools pull request #2
Opened 2021-07-11 13:11 UTC by mocnik-science

2021-07-16 17:15 UTC, ad2476 commented on README.md
> +Currently, the following gazetter services are supported: OpenStreetMap [Nominatim](http://nominatim.openstreetmap.org), [Geonames](http://www.geonames.org/). I aim to support additional gazetteer se
```suggestion
Currently, the following gazetter services are supported: OpenStreetMap [Nominatim](http://nominatim.openstreetmap.org), [Geonames](http://www.geonames.org/). Endpoint implementations rely on the internal `CacheObject` to comply with API rate limits and obligations of clients to cache requests.
```

2021-07-16 17:16 UTC, ad2476 commented on README.md
> +This fork, in the following referred to as `GeocodingTools`, **heavily** builds on Franz-Benjamin Mocnik's [OSMPythonTools](https://github.com/mocnik-science/osm-python-tools) library. In my role as
```suggestion
This fork, heavily builds on Franz-Benjamin Mocnik's [OSMPythonTools](https://github.com/mocnik-science/osm-python-tools) library. I have extended the original code and documentation to allow querying the Geonames service.
```

2021-07-16 17:19 UTC, ad2476 requested changes
This fork has been mostly dead, so I'd not like to promise future development. If it's caused confusion about the original, happy to merge this PR to clarify.

2021-07-18 06:04 UTC, mocnik-science commented on README.md
> +This fork, in the following referred to as `GeocodingTools`, **heavily** builds on Franz-Benjamin Mocnik's [OSMPythonTools](https://github.com/mocnik-science/osm-python-tools) library. In my role as
fine with it.

2021-07-18 06:04 UTC, mocnik-science commented on README.md
> +This fork, in the following referred to as `GeocodingTools`, **heavily** builds on Franz-Benjamin Mocnik's [OSMPythonTools](https://github.com/mocnik-science/osm-python-tools) library. In my role as
Thanks

2021-07-18 06:05 UTC, mocnik-science commented
Feel welcome to merge.

2021-07-18 06:06 UTC, mocnik-science commented
Thanks for your quick reaction.

(And please do not forget to adapt the "About" message like proposed by me.  Thanks!

2021-07-24 01:00 UTC, merged